import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ReportData {
  userName: string
  userEmail: string
  lessonTitle: string
  practiceCode: string
  practiceResult: string
}

export async function generateModuleReport(data: ReportData) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header Background
  doc.setFillColor(13, 17, 23)
  doc.rect(0, 0, pageWidth, 40, 'F')

  // Logo (SRM)
  try {
    const logoImg = '/srm-logo.png'
    doc.addImage(logoImg, 'PNG', 15, 10, 40, 20)
  } catch (e) {
    console.error('Logo failed to load', e)
  }

  // Title
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('Module Verification Report', pageWidth - 15, 20, { align: 'right' })
  
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('DataQuest eLab - Practical Lab Execution', pageWidth - 15, 28, { align: 'right' })

  // User Info Section
  doc.setTextColor(33, 37, 41)
  doc.setFontSize(12)
  doc.text(`Student: ${data.userName}`, 15, 55)
  doc.text(`Email: ${data.userEmail}`, 15, 62)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, 69)
  
  doc.setFont('helvetica', 'bold')
  doc.text(`Module: ${data.lessonTitle}`, 15, 80)
  doc.line(15, 82, 195, 82)

  // Practice Code
  doc.setFontSize(14)
  doc.text('1. Practical Execution (Sandbox Verified)', 15, 95)
  
  doc.setFontSize(10)
  doc.setFont('courier', 'normal')
  const splitCode = doc.splitTextToSize(data.practiceCode, 180)
  doc.setDrawColor(200, 200, 200)
  doc.setFillColor(248, 249, 250)
  
  // Adjusted height for code box
  const boxHeight = Math.min(splitCode.length * 5 + 10, 150)
  doc.rect(15, 100, 180, boxHeight, 'FD')
  doc.text(splitCode.slice(0, 30), 20, 108) 

  const statusY = 100 + boxHeight + 15
  doc.setFont('helvetica', 'bold')
  doc.text('Status:', 15, statusY)
  doc.setTextColor(63, 185, 80)
  doc.text('VERIFIED - ALL TEST CASES PASSED', 35, statusY)

  // Disclaimer
  doc.setTextColor(248, 81, 73)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'italic')
  const disclaimer = 'IMPORTANT: Please download and save this PDF immediately. DataQuest eLab operates on a decentralized architecture; your progress data is stored exclusively in your browser cache and will be lost if the cache is cleared.'
  const splitDisclaimer = doc.splitTextToSize(disclaimer, 180)
  doc.text(splitDisclaimer, 15, 280)

  // Footer
  doc.setTextColor(139, 148, 158)
  doc.setFontSize(8)
  doc.text('Generated by DataQuest eLab Decentralized Learning Engine', pageWidth / 2, 290, { align: 'center' })

  doc.save(`${data.userName.replace(/\s+/g, '_')}_${data.lessonTitle.replace(/\s+/g, '_')}_Report.pdf`)
}
